### ISSUE TITLE
Official image max-size implementation

### ISSUE THREAD

**Issue by legowerewolf** [legowerewolf/AO3-themes#6]
Figure out how it's implemented and decide if my implementation is better (and should be kept) or unnecessary.

**Comment by legowerewolf** [comment]
It seems like the max-size implementation is based on 
```css
.userstuff img {
    max-width: 100%;
    height: auto;
}
```
whereas mine compiles to
```
div.userstuff img {
  width: 90%;
  height: auto;
  margin-left: 5%;
  margin-right: 5%;
}
```
